/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_OUT_PB_H_INCLUDED
#define PB_OUT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Tx_out {
    pb_callback_t signedTx;
/* @@protoc_insertion_point(struct:Tx_out) */
} Tx_out;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Tx_out_init_default                      {{{NULL}, NULL}}
#define Tx_out_init_zero                         {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Tx_out_signedTx_tag                      1

/* Struct field encoding specification for nanopb */
extern const pb_field_t Tx_out_fields[2];

/* Maximum encoded size of messages (where known) */
/* Tx_out_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define OUT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif