/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "simple.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const pb_field_t Tx_in_fields[5] = {
    PB_FIELD(1, STRING, SINGULAR, CALLBACK, FIRST, Tx_in, sighashes, sighashes, 0),
    PB_FIELD(2, STRING, SINGULAR, CALLBACK, OTHER, Tx_in, walletPath, sighashes, 0),
    PB_FIELD(3, STRING, SINGULAR, CALLBACK, OTHER, Tx_in, address, walletPath, 0),
    PB_FIELD(4, INT64, SINGULAR, STATIC, OTHER, Tx_in, amount, address, 0),
    PB_LAST_FIELD};

/* @@protoc_insertion_point(eof) */